### PR TITLE
Appium sendkeys suggestion

### PR DESCRIPTION
**Pull request by Abdulaziz-rgb**
1. Removed blank lines in some files
2.  Proposed change in SendKeys method. Send keys is not working in my case. Using Actions is recommended approach in working with Appium. Hence, I created this PR

### CODE REVIEW

**Review by khayitmuradov — COMMENTED** [review]
it has some conflicts

**Comment by Abdulaziz-rgb** [comment]
Did you import required packages?

**Comment by evgkas** [comment]
I see a problem here. In my code active and inactive search fields are different elements. So I cant send keys to the search field using this method. And that's the reason why I do not implement click to the previous method (and with click it maybe a step).
Do you perform a click to the field before sendkeys in your case?

**Comment by Abdulaziz-rgb** [comment]
> I see a problem here. In my code active and inactive search fields are different elements. So I cant send keys to the search field using this method. And that's the reason why I do not implement click to the previous method (and with click it maybe a step). Do you perform a click to the field before sendkeys in your case?

Yeah I am using explicitly clicking element and sending key using Actions

**Comment by Abdulaziz-rgb** [comment]
Is it working in your laps?

**Review by evgkas — APPROVED** [review]

**Review by NikitaGavruk — APPROVED** [review]

**Pull request merged**
